# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: KubeForge API CI

on:
  push:
    paths:
      - "apps/api/**"
    branches: ["main"]
  pull_request:
    paths:
      - "apps/api/**"
    branches: ["main"]

defaults:
  run:
    working-directory: apps/api

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0" # Fetches all history so the action can find the previous tag

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: apps/api/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run lint

      # - name: Run tests
      #   run: npm test

      # - name: Run test coverage
      #   run: npm run test:coverage
